import { JobOpportunity, GovernmentScheme, LearningCourse, ApplicationRecord, AuditLogEntry, SystemHealthMetric, CompanyProfile } from '../types';

export const DEMO_COMPANIES: CompanyProfile[] = [
  {
    id: 'comp-1',
    companyName: 'Nexus Supply Chain Logistics Pvt Ltd',
    industry: 'Logistics & Supply Chain',
    cinGstin: 'U63090KA2014PTC078912 / 29AAACN1234F1Z5',
    website: 'https://nexuslogistics.example.in',
    officialEmail: 'veteran-careers@nexuslogistics.example.in',
    officialPhone: '+91 80 4123 9800',
    country: 'India',
    state: 'Karnataka',
    city: 'Bengaluru',
    hqLocation: 'Bengaluru, Karnataka',
    companySize: '1,000-5,000 Employees',
    recruiterName: 'Kavita Sundaram',
    recruiterDesignation: 'Head of Veteran Talent & D&I',
    description: 'Tier-1 supply chain enterprise operating 42 fulfillment hubs across India. Actively recruiting veterans for fleet governance, warehouse command, and dispatch safety.',
    companyInformation: 'Nexus Logistics is a premier national supply chain network managing over 5 million square feet of automated and regional warehousing across metropolitan and tier-2 corridors.',
    veteranHiringInfo: 'Established "Sena to Corporate" bridge initiative with tailored onboarding, rank-to-grade mapping, and senior veteran mentorship.',
    internshipInfo: '6-month operational transition internships for transitioning defense personnel, focusing on SAP ERP and modern telematics.',
    apprenticeshipInfo: '1-year corporate logistics apprenticeship tailored for Agniveer cohorts with guaranteed placement opportunities.',
    accessibilityInfo: 'All primary hubs equipped with barrier-free ramps, tactile flooring, and ergonomic workstations for service-disabled veterans.',
    workplaceDescription: 'Dynamic, high-trust operational command centers and fulfillment facilities where integrity, safety, and punctual execution are paramount.',
    careerOpportunitiesDescription: 'Direct pathways into Warehouse Hub Management, Regional Fleet Operations, Transit Safety Auditing, and Vendor Operations.',
    skillsLookedForDescription: 'Team leadership under pressure, inventory audit rigor, convoy/fleet scheduling, and commitment to zero-incident safety protocols.',
    veteranInitiativesDescription: 'Peer veteran buddy program, paid leave for annual ECHS medical reviews, and celebration of Armed Forces Day across all sites.',
    internshipProgramsDescription: 'Rotational 24-week internship across Hub Receiving, Telemetry Dispatch, Fleet Maintenance, and Client SLA Management.',
    apprenticeshipProgramsDescription: 'Dual-certificate corporate logistics apprenticeship recognized under National Apprenticeship Promotion Scheme (NAPS).',
    trainingOpportunitiesDescription: 'Sponsored Six Sigma Green Belt, APICS supply chain certifications, and corporate digital communication masterclasses.',
    applicationProcessDescription: 'Stage 1: Direct civilian profile review on ValorBadge → Stage 2: Technical/operations panel briefing → Stage 3: Leadership culture discussion and compensation alignment.',
    verificationStatus: 'verified',
    veteranHiringPledge: true,
    totalOpenings: 14,
    reservedCohortQuota: '15% dedicated reservation for Armed Forces Veterans & Agniveers',
    workplaceAccommodationsOffered: ['Ergonomic desk setups', 'Wheelchair accessibility in major distribution centers', 'Dedicated peer veteran transition buddy'],
    lastAuditDate: '2026-02-15',
    isDemoData: true,
    isCompanyAuthored: true
  },
  {
    id: 'comp-2',
    companyName: 'Bharat Electronics Limited (BEL)',
    industry: 'Defense Electronics & Aerospace (PSU Navratna)',
    cinGstin: 'L32309KA1954GOI000787 / 29AAACB1456D1Z1',
    website: 'https://bel-india.in',
    officialEmail: 'esm-cell@bel-india.in',
    officialPhone: '+91 80 2503 9300',
    country: 'India',
    state: 'Karnataka',
    city: 'Bengaluru',
    hqLocation: 'Bengaluru, Karnataka',
    companySize: '5,000+ Employees',
    recruiterName: 'Col. R. S. Pathania (Retd.)',
    recruiterDesignation: 'Chief Officer — Ex-Servicemen Welfare & Recruitment Cell',
    description: 'Premier Navratna Defence Public Sector Undertaking under the Ministry of Defence, Government of India. Designs and produces advanced electronic warfare, radar, and avionics systems.',
    companyInformation: 'Bharat Electronics Limited is an Indian state-owned aerospace and defense electronics company with 9 manufacturing units and multiple regional offices across India.',
    veteranHiringInfo: 'Implements official reservation rules and dedicated Agniveer lateral absorption quotas under Department of Public Enterprises guidelines.',
    internshipInfo: 'Post-service vocational orientation programs in radar servicing, microwave instrumentation, and defense electronics assembly.',
    apprenticeshipInfo: 'National Apprentice Certificate (NAC) streams across electrical, mechanical, and electronic trades in BEL production units.',
    accessibilityInfo: 'PSU-standard 100% barrier-free facilities with accessible restrooms, electric shuttles, and specialized assistive technology.',
    workplaceDescription: 'Research, precision assembly, and testing laboratories adhering to international defense manufacturing quality standards.',
    careerOpportunitiesDescription: 'Technical Officer, Quality Assurance Manager, Security Executive, Field Support Engineer, and Testing Technicians.',
    skillsLookedForDescription: 'Radar maintenance, electronic warfare systems upkeep, quality assurance procedures, disciplined technical reporting, and team supervision.',
    veteranInitiativesDescription: 'Ex-Servicemen Welfare Board, active DGR liaison officer, and medical facilities through BEL Hospital complex.',
    internshipProgramsDescription: 'Practical exposure to indigenous defense communication equipment, PCB prototyping, and flight simulator maintenance.',
    apprenticeshipProgramsDescription: 'Apprenticeship Act 1961 compliant industrial training with comprehensive monthly stipend and medical coverage.',
    trainingOpportunitiesDescription: 'Advanced electro-optics calibration, ISO/IEC 17025 laboratory quality training, and defense project management.',
    applicationProcessDescription: 'Stage 1: Official application via ValorBadge or BEL portal → Stage 2: Written test / skill assessment → Stage 3: Verification of discharge book and qualifications.',
    verificationStatus: 'verified',
    veteranHiringPledge: true,
    totalOpenings: 28,
    reservedCohortQuota: 'Statutory DGR/ESM quota in Executive & Non-Executive grades as per MoD directives',
    workplaceAccommodationsOffered: ['Full barrier-free PSU campus', 'Assistive technology labs', 'ECHS/Medical dispensary on premises'],
    lastAuditDate: '2026-03-01',
    isDemoData: true,
    isCompanyAuthored: true
  },
  {
    id: 'comp-3',
    companyName: 'AeroTech Industrial Manufacturing Ltd',
    industry: 'Industrial Engineering & Heavy Manufacturing',
    cinGstin: 'U29253PN2010PLC134882 / 27AAACA9876C1Z4',
    website: 'https://aerotechmfg.example.in',
    officialEmail: 'talent@aerotechmfg.example.in',
    officialPhone: '+91 20 6711 4500',
    country: 'India',
    state: 'Maharashtra',
    city: 'Pune',
    hqLocation: 'Pune, Maharashtra',
    companySize: '500-1,000 Employees',
    recruiterName: 'Arjun Mehra',
    recruiterDesignation: 'Senior Talent Acquisition Manager — Technical Operations',
    description: 'Precision mechanical engineering facility manufacturing defense sub-assemblies and industrial machinery. Dedicated track for EME and Corps of Engineers personnel.',
    companyInformation: 'Specialists in CNC multi-axis machining, robotic welding, and aerospace-grade metallurgical components supplying global prime contractors.',
    veteranHiringInfo: 'Targeted recruitment pipeline for Corps of Electronics and Mechanical Engineers (EME) and Indian Navy Marine Engineering artificers.',
    internshipInfo: '4-month hands-on industry acclimatization for retiring technicians with focus on modern industrial CAD/CAM.',
    apprenticeshipInfo: 'Precision engineering apprenticeship with fast-track conversion to Assistant Plant Supervisor.',
    accessibilityInfo: 'Step-free manufacturing floor with automated component shuttles and zero-strain hydraulic lifting aids.',
    workplaceDescription: 'Modern ISO 9001:2015 and AS9100 certified smart factory environment focused on engineering excellence and team safety.',
    careerOpportunitiesDescription: 'Maintenance Engineers, Tool Room Supervisors, Quality Control Inspectors, and Heavy Plant Operations Specialists.',
    skillsLookedForDescription: 'Preventative machine maintenance, hydraulics, pneumatic systems, safety compliance, and technician crew management.',
    veteranInitiativesDescription: 'Rank-neutral workplace culture, technical cross-skilling allowances, and full family medical insurance.',
    internshipProgramsDescription: 'Practical rotation across Heavy CNC machining, Heat Treatment, Non-Destructive Testing, and Preventive Maintenance.',
    apprenticeshipProgramsDescription: 'Government-approved dual training scheme in Mechatronics and Industrial Automation.',
    trainingOpportunitiesDescription: 'Certification in Siemens PLC programming, Fanuc CNC controllers, and Six Sigma Yellow/Green Belt.',
    applicationProcessDescription: 'Stage 1: ValorBadge civilian skill profile screening → Stage 2: Practical technical walk-through → Stage 3: Direct offer and relocation assistance.',
    verificationStatus: 'verified',
    veteranHiringPledge: true,
    totalOpenings: 9,
    reservedCohortQuota: 'Priority interview program for military engineering technicians',
    workplaceAccommodationsOffered: ['Adjustable workstations', 'Zero-hazard automated floor transit'],
    lastAuditDate: '2026-01-20',
    isDemoData: true,
    isCompanyAuthored: true
  },
  {
    id: 'comp-4',
    companyName: 'CloudWave Telemetry Solutions',
    industry: 'IT, Cloud Infrastructure & Cybersecurity',
    cinGstin: 'U72200HR2018PTC065431 / 06AAACC7788P1ZZ',
    website: 'https://cloudwave.example.com',
    officialEmail: 'careers@cloudwave.example.com',
    officialPhone: '+91 124 456 7890',
    country: 'India',
    state: 'Haryana',
    city: 'Gurugram',
    hqLocation: 'Gurugram, Haryana',
    companySize: '200-500 Employees',
    recruiterName: 'Neha Deshmukh',
    recruiterDesignation: 'Lead Technical Recruiter — Infrastructure & Cloud',
    description: 'Mission-critical cloud telemetry and network uptime operations monitoring for global enterprise clients. Special recruiting stream for Corps of Signals and radar specialists.',
    companyInformation: 'CloudWave provides 24x7 Network Operations Center (NOC) and Security Operations Center (SOC) telemetry for international enterprise infrastructure.',
    veteranHiringInfo: 'Fast-track transition stream translating defense telecom, signals, and radar maintenance experience into Cloud SRE and SOC monitoring roles.',
    internshipInfo: '12-week cloud monitoring Bootcamp with complete AWS and Azure practitioner certification sponsorship.',
    apprenticeshipInfo: 'Junior Cloud Network Administrator apprenticeship program tailored for Agniveer Signals cohorts.',
    accessibilityInfo: '100% remote-first infrastructure with assistive screen reading, speech recognition, and accessible communication tools.',
    workplaceDescription: 'Remote-first, collaborative engineering culture prioritizing objective incident resolution, continuous learning, and empathetic team dynamics.',
    careerOpportunitiesDescription: 'NOC Incident Controller, Cloud Monitoring Analyst, Junior SOC Analyst, Network Systems Administrator.',
    skillsLookedForDescription: 'Network troubleshooting, disciplined shift handover, incident triage, protocol adherence, and clear crisis documentation.',
    veteranInitiativesDescription: 'Flexible work hours for medical appointments, home workstation ergonomics stipend, and peer veteran support group.',
    internshipProgramsDescription: 'Intensive real-time monitoring simulation, incident playbook execution, and cloud architecture fundamentals.',
    apprenticeshipProgramsDescription: 'Practical junior administrator track with direct mentorship from Principal Infrastructure Engineers.',
    trainingOpportunitiesDescription: 'Full coverage for CompTIA Security+, AWS Certified Cloud Practitioner, and Linux Professional Institute certifications.',
    applicationProcessDescription: 'Stage 1: Profile review on ValorBadge → Stage 2: 45-minute virtual technical discussion → Stage 3: HR briefing and welcome aboard.',
    verificationStatus: 'verified',
    veteranHiringPledge: true,
    totalOpenings: 18,
    reservedCohortQuota: 'Active Agniveer Tech Track for junior signals and communication trades',
    workplaceAccommodationsOffered: ['100% remote work infrastructure', 'Screen-reader & magnification software', 'Ergonomic home workstation allowance'],
    lastAuditDate: '2026-02-28',
    isDemoData: true,
    isCompanyAuthored: true
  },
  {
    id: 'comp-5',
    companyName: 'Apex FastLog Retail Warehouses',
    industry: 'E-Commerce Fulfillment & Operations',
    cinGstin: 'U52100TG2016PTC089123 / 36AAACA4321Q1Z8',
    website: 'https://apexfastlog.example.in',
    officialEmail: 'agniveer-intake@apexfastlog.example.in',
    officialPhone: '+91 40 3987 6540',
    country: 'India',
    state: 'Telangana',
    city: 'Hyderabad',
    hqLocation: 'Hyderabad, Telangana',
    companySize: '5,000+ Employees',
    recruiterName: 'Vikramaditya Rao',
    recruiterDesignation: 'Director of Talent Partnerships & Veteran Hiring',
    description: 'Rapid grocery and retail fulfillment center chain operating automated robotic warehouses. Focuses heavily on Agniveer transition internships and apprenticeships.',
    companyInformation: 'Apex FastLog powers next-generation robotic fulfillment hubs across 22 Indian cities, fulfilling over 200,000 orders every 24 hours.',
    veteranHiringInfo: 'Pioneering Agniveer lateral entry pipeline with fast-track supervisory promotions and dedicated transition mentorship.',
    internshipInfo: '8-week warehouse shift lead internship providing hands-on management experience in automated fulfillment.',
    apprenticeshipInfo: '1-year Retail Operations & Logistics Apprenticeship with stipend and performance bonuses.',
    accessibilityInfo: 'Ergonomic packing benches, motorized material handlers, and wheelchair accessible supervisory stations.',
    workplaceDescription: 'Technology-enabled logistics hubs driven by automation, teamwork, physical fitness, and operational discipline.',
    careerOpportunitiesDescription: 'Shift Operations Supervisor, Quality Audit Specialist, Inbound Fleet Coordinator, Inventory Control Specialist.',
    skillsLookedForDescription: 'High energy, punctual shift leadership, quick decision making under pressure, and fair team delegation.',
    veteranInitiativesDescription: 'Uniformed service transition allowance, fast-track career appraisal cycles, and subsidized family health coverage.',
    internshipProgramsDescription: 'Rotation through high-density sorting, reverse logistics, automated conveyor operations, and safety inspections.',
    apprenticeshipProgramsDescription: 'Government-certified logistics training with guaranteed permanent supervisor placement upon completion.',
    trainingOpportunitiesDescription: 'Forklift operator safety certification, Warehouse Management System (WMS) administration, and First Aid mastery.',
    applicationProcessDescription: 'Stage 1: ValorBadge application → Stage 2: Facility walk-through and briefing → Stage 3: Onboarding orientation.',
    verificationStatus: 'verified',
    veteranHiringPledge: true,
    totalOpenings: 35,
    reservedCohortQuota: 'Annual cohort intake for 100+ Agniveers with fast-track promotion to Hub Manager',
    workplaceAccommodationsOffered: ['Ergonomic conveyor packing stations', 'Automated pallet movers'],
    lastAuditDate: '2026-02-10',
    isDemoData: true,
    isCompanyAuthored: true
  },
  {
    id: 'comp-6',
    companyName: 'Sentinel Defense Cyber Labs',
    industry: 'Cyber Defense & Critical Infrastructure Security',
    cinGstin: 'U72900KA2021PTC145678 / 29AAACS5544R1Z3',
    website: 'https://sentinelcyberlabs.example.in',
    officialEmail: 'security-hiring@sentinelcyberlabs.example.in',
    officialPhone: '+91 80 4950 1122',
    country: 'India',
    state: 'Karnataka',
    city: 'Bengaluru',
    hqLocation: 'Bengaluru, Karnataka',
    companySize: '51-200 Employees',
    recruiterName: 'Ananya Roy',
    recruiterDesignation: 'Head of Talent & Strategic Security Hiring',
    description: 'Specialized cyber intelligence firm securing national power grids, banking rails, and defense telemetry. 100% accessible desk-based workflows.',
    companyInformation: 'Dedicated threat intelligence, threat hunting, and defensive perimeter operations firm founded by cybersecurity researchers and military veterans.',
    veteranHiringInfo: 'Veteran-first hiring charter actively translating military signals, radar, intelligence, and radio discipline into digital cyber operations.',
    internshipInfo: '16-week cyber security analyst residency with live defensive range exercises and purple-team simulations.',
    apprenticeshipInfo: 'Junior Cyber Defense Operator apprenticeship for veterans with IT or signals background.',
    accessibilityInfo: 'Fully remote-ready environment, screen reader compatibility, adjustable contrast dark interfaces, and asynchronous communication.',
    workplaceDescription: 'Intellectually rigorous, calm, desk-based security command center where precision, focus, and analytical thinking thrive.',
    careerOpportunitiesDescription: 'SOC Tier-1/2 Analyst, Threat Intelligence Researcher, Incident Response Specialist, Compliance Auditor.',
    skillsLookedForDescription: 'Analytical problem solving, pattern recognition, disciplined logging, operational security (OPSEC) mindset, and integrity.',
    veteranInitiativesDescription: '100% remote flexibility for veterans with physical disabilities, mental health counseling support, and continuous training subsidies.',
    internshipProgramsDescription: 'Guided threat analysis, SIEM log triage, malware analysis basics, and defense network hardening.',
    apprenticeshipProgramsDescription: 'Dual training in enterprise digital defense with full financial sponsorship for global cybersecurity credentials.',
    trainingOpportunitiesDescription: 'Sponsored Certified Ethical Hacker (CEH), CompTIA CySA+, and Blue Team Level 1 certifications.',
    applicationProcessDescription: 'Stage 1: Secure civilian profile screening on ValorBadge → Stage 2: Practical technical scenario assessment → Stage 3: Founder interview.',
    verificationStatus: 'verified',
    veteranHiringPledge: true,
    totalOpenings: 6,
    reservedCohortQuota: 'Veteran-first hiring charter for intelligence and electronic warfare veterans',
    workplaceAccommodationsOffered: ['Fully remote-first setup', 'Flexible medical visit scheduling', 'Screen reader and speech-to-text integration'],
    lastAuditDate: '2026-03-05',
    isDemoData: true,
    isCompanyAuthored: true
  }
];

export const DEMO_JOBS: JobOpportunity[] = [
  {
    id: 'demo-job-1',
    title: 'Operations & Fleet Logistics Manager',
    company: 'Nexus Supply Chain Logistics Pvt Ltd',
    location: 'Bengaluru, Karnataka',
    country: 'IN',
    state: 'Karnataka',
    type: 'full-time',
    sector: 'private',
    workplaceType: 'hybrid',
    industry: 'Logistics',
    experienceLevel: '5-8 Years Service',
    educationRequired: 'Graduate / Army Special Certificate',
    salaryRange: '₹12,00,000 - ₹16,00,000 / annum',
    minSalary: 1200000,
    maxSalary: 1600000,
    description: 'Lead multi-modal distribution, hub operations, vendor governance, and dispatch safety across South India distribution network. Directs shift planning, transit safety adherence, and vehicle telematics.',
    eligibilitySummary: 'Ideal for ex-JCOs, NCOs, or Officers from Army Service Corps (ASC), Air Force Logistics, or Indian Navy Logistics Branch with convoy, fleet, or depot management experience.',
    applicationProcess: 'Stage 1: ValorBadge civilian profile screening → Stage 2: Operations case briefing → Stage 3: Leadership culture interview with Vice President of Supply Chain.',
    officialUrl: 'https://nexuslogistics.example.in/careers/ops-mgr',
    veteranFriendlyScore: 96,
    civilianSkillsMatched: ['Multi-node Supply Chain', 'Inventory Audit & SLA', 'Fleet Maintenance Protocol', 'High-pressure Crisis Operations'],
    militaryBackgroundSuitability: ['ASC / Logistics', 'Transport Units', 'Quartermaster Operations'],
    postedDate: '2 days ago',
    isVerifiedEmployer: true,
    verificationStatus: 'verified',
    isAccessibleRole: true,
    isVeteranFriendly: true,
    status: 'active',
    isDemoData: true,
  },
  {
    id: 'demo-job-2',
    title: 'Deputy General Manager (Security & Asset Protection)',
    company: 'Bharat Electronics Limited (BEL)',
    location: 'Bengaluru, Karnataka',
    country: 'IN',
    state: 'Karnataka',
    type: 'full-time',
    sector: 'psu',
    workplaceType: 'on-site',
    industry: 'Defense Tech / PSU',
    experienceLevel: '10+ Years Service (Commissioned / Senior JCO)',
    educationRequired: 'Graduation from recognized university or Defence Academy degree',
    salaryRange: '₹18,50,000 - ₹24,00,000 / annum (E-5 Pay Scale + PSU Perks)',
    minSalary: 1850000,
    maxSalary: 2400000,
    description: 'Direct physical security, perimeter surveillance systems, intelligence liaison, industrial safety, and executive protection protocols across BEL manufacturing campuses. Ensure strict adherence to Official Secrets Act and ISO 27001 physical security standards.',
    eligibilitySummary: 'Released Commissioned Officers or Senior JCOs from Indian Army, Navy, or Air Force with honorable discharge. Age relaxations applicable as per Central Govt ESM reservation guidelines.',
    applicationProcess: 'Step 1: Submit application via ValorBadge or DGR portal → Step 2: Verification of Service Discharge Dossier → Step 3: Formal interview panel at BEL Corporate Office.',
    officialUrl: 'https://bel-india.in/careers/deputy-gm-security-esm',
    veteranFriendlyScore: 99,
    civilianSkillsMatched: ['Critical Infrastructure Security', 'Access Control Systems', 'Crisis Command', 'Statutory Intelligence Liaison'],
    militaryBackgroundSuitability: ['Infantry', 'Corps of Military Police (CMP)', 'Combat Arms', 'Provost Units'],
    postedDate: '1 day ago',
    isVerifiedEmployer: true,
    verificationStatus: 'verified',
    isAccessibleRole: false,
    isVeteranFriendly: true,
    status: 'active',
    isDemoData: true,
  },
  {
    id: 'demo-job-3',
    title: 'Senior Network Operations Center (NOC) Analyst',
    company: 'CloudWave Telemetry Solutions',
    location: 'Gurugram, Haryana / Remote',
    country: 'IN',
    state: 'Haryana',
    type: 'full-time',
    sector: 'private',
    workplaceType: 'hybrid',
    industry: 'IT & Cybersecurity',
    experienceLevel: '4-7 Years Service',
    educationRequired: 'Diploma in Electronics / Signals or B.Tech / B.Sc Computer Science',
    salaryRange: '₹14,00,000 - ₹18,50,000 / annum',
    minSalary: 1400000,
    maxSalary: 1850000,
    description: 'Monitor mission-critical cloud infrastructure, triage network anomalies, maintain incident runbooks. Highly suited for Corps of Signals or radar/telecom technicians seeking civilian IT engineering roles.',
    eligibilitySummary: 'Ex-servicemen or Agniveers with communication, electronic Warfare, radar, or tactical data link operational backgrounds.',
    applicationProcess: 'Online technical assessment (networking basics) followed by a 45-minute virtual conversation with NOC Engineering Lead.',
    officialUrl: 'https://cloudwave.example.com/careers/noc-analyst',
    veteranFriendlyScore: 98,
    civilianSkillsMatched: ['RF/Microwave & Fiber Systems', 'Incident Triage & Root Cause', 'Network Topology Diagnostics', 'Zero-Downtime Operations'],
    militaryBackgroundSuitability: ['Corps of Signals', 'Naval Communications', 'Air Force Radar/Avionics'],
    postedDate: '1 week ago',
    isVerifiedEmployer: true,
    verificationStatus: 'verified',
    isAccessibleRole: true,
    isVeteranFriendly: true,
    status: 'active',
    isDemoData: true,
  },
  {
    id: 'demo-job-4',
    title: 'Operations Management Trainee (Agniveer Special Track)',
    company: 'Apex FastLog Retail Warehouses',
    location: 'Hyderabad, Telangana',
    country: 'IN',
    state: 'Telangana',
    type: 'internship',
    sector: 'private',
    workplaceType: 'on-site',
    industry: 'Operations',
    experienceLevel: '1-4 Years Service (Agniveer Cohort)',
    educationRequired: '10+2 / Intermediate with Agniveer Skill Certificate',
    salaryRange: '₹38,000 - ₹48,000 / month (Stipend + Meal Allowance)',
    minSalary: 456000,
    maxSalary: 576000,
    description: 'Fast-track transition internship designed to translate military discipline, shift coordination, equipment accountability, and team drills into modern fulfillment center team lead positions within 6 months.',
    eligibilitySummary: 'Exclusively open to certified Agniveers (Army, Navy, Air Force) completing their 4-year tenure. Full absorption into permanent Assistant Warehouse Manager grade upon completion.',
    applicationProcess: 'Direct registration via ValorBadge → Verification of Agniveer Skill Certificate → Walk-in orientation & operational simulation.',
    officialUrl: 'https://apexfastlog.example.in/agniveer-pathway',
    veteranFriendlyScore: 99,
    civilianSkillsMatched: ['Shift Roster & Punctuality', 'Inventory Discrepancy Reconciliation', 'Team Motivation', 'Safe Handling Standards'],
    militaryBackgroundSuitability: ['All Service Arms (Agniveer 4-Year Veterans)'],
    postedDate: 'Yesterday',
    isVerifiedEmployer: true,
    verificationStatus: 'verified',
    isAccessibleRole: false,
    isVeteranFriendly: true,
    status: 'active',
    isDemoData: true,
  },
  {
    id: 'demo-job-5',
    title: 'Advanced Electro-Mechanical Apprenticeship (National Apprenticeship Scheme)',
    company: 'AeroTech Industrial Manufacturing Ltd',
    location: 'Pune, Maharashtra',
    country: 'IN',
    state: 'Maharashtra',
    type: 'apprenticeship',
    sector: 'private',
    workplaceType: 'on-site',
    industry: 'Manufacturing',
    experienceLevel: 'Agniveer or 1-5 Years Service',
    educationRequired: 'ITI / Army Class-1 Trade Certificate in Fitter/Machinist/Electrical',
    salaryRange: '₹28,000 - ₹34,000 / month (Govt NAPS stipend + Corporate supplement)',
    minSalary: 336000,
    maxSalary: 408000,
    description: '1-year certified industrial apprenticeship program under the National Apprenticeship Promotion Scheme (NAPS). Hands-on training on 5-axis CNC machining, hydraulic maintenance, and precision defense hardware assembly.',
    eligibilitySummary: 'Corps of Electrical & Mechanical Engineers (EME), Navy Artificers, Air Force Mechanical Transport/Airframe Technicians, or technical Agniveers.',
    applicationProcess: 'NAPS Portal Registration (apprenticeshipindia.gov.in) with company code AT-IND-2026. Trade skill practical evaluation.',
    officialUrl: 'https://aerotechmfg.example.in/apprenticeships',
    veteranFriendlyScore: 95,
    civilianSkillsMatched: ['Hydraulic Maintenance', 'CNC Operation & Tooling', 'Quality Inspection', 'Industrial Safety Standards'],
    militaryBackgroundSuitability: ['EME', 'Naval Engineering', 'Air Force Mechanical'],
    postedDate: '3 days ago',
    isVerifiedEmployer: true,
    verificationStatus: 'verified',
    isAccessibleRole: false,
    isVeteranFriendly: true,
    status: 'active',
    isDemoData: true,
  },
  {
    id: 'demo-job-6',
    title: 'Remote Cyber Threat Intelligence & Incident Analyst',
    company: 'Sentinel Defense Cyber Labs',
    location: 'Remote (Pan-India)',
    country: 'IN',
    state: 'Karnataka',
    type: 'full-time',
    sector: 'private',
    workplaceType: 'remote',
    industry: 'Cybersecurity',
    experienceLevel: '2+ Years Service',
    educationRequired: 'Graduation in any discipline or Signals Technical Trade Equivalent',
    salaryRange: '₹10,50,000 - ₹15,00,000 / annum',
    minSalary: 1050000,
    maxSalary: 1500000,
    description: '100% remote desk role analyzing security incidents, threat telemetry, and security playbooks. Fully accessible for war-disabled veterans, locomotor impaired personnel, and remote work preference.',
    eligibilitySummary: 'Suitable for ex-service personnel from Signals, Intelligence, Navy, or Air Force with basic familiarity with digital workflows and analytical discipline. Training in SIEM tools provided.',
    applicationProcess: 'Online aptitude review → Take-home threat scenario analysis → Virtual interview with Cyber Operations Lead.',
    officialUrl: 'https://sentinelcyberlabs.example.in/careers/remote-soc',
    veteranFriendlyScore: 98,
    civilianSkillsMatched: ['Threat Triaging', 'Log Telemetry Analysis', 'SOP Adherence', 'Information Integrity'],
    militaryBackgroundSuitability: ['Corps of Signals', 'Intelligence Corps', 'Air Force Technical', 'Any Service Branch with IT Interest'],
    postedDate: 'Today',
    isVerifiedEmployer: true,
    verificationStatus: 'verified',
    isAccessibleRole: true,
    isVeteranFriendly: true,
    status: 'active',
    isDemoData: true,
  },
  {
    id: 'demo-job-7',
    title: 'Digital Logistics Dispatch & Vendor Compliance Coordinator',
    company: 'TransIndia Freight Logistics',
    location: 'Bengaluru / Hybrid',
    country: 'IN',
    state: 'Karnataka',
    type: 'full-time',
    sector: 'private',
    workplaceType: 'hybrid',
    industry: 'Logistics',
    experienceLevel: '3+ Years Service',
    educationRequired: 'Graduation or Army Education Certificate',
    salaryRange: '₹8,00,000 - ₹11,50,000 / annum',
    minSalary: 800000,
    maxSalary: 1150000,
    description: 'Digital tracking, carrier communication, and dispatch documentation. Office facility is 100% wheelchair accessible with ergonomic workstation accommodations provided.',
    eligibilitySummary: 'Ideal for veterans with supply chain, inventory record-keeping, or convoy dispatch experience who prefer desk-oriented coordination.',
    applicationProcess: 'Submit ValorBadge profile → Initial telephonic conversation → Office accessibility walkthrough & interview.',
    officialUrl: 'https://transindiafreight.example.com/careers/dispatch-coordinator',
    veteranFriendlyScore: 95,
    civilianSkillsMatched: ['Dispatch Coordination', 'Vendor SLA Audits', 'Documentation Accuracy', 'Carrier Communications'],
    militaryBackgroundSuitability: ['Army Service Corps', 'Naval Stores', 'Air Force Equipment'],
    postedDate: '3 days ago',
    isVerifiedEmployer: true,
    verificationStatus: 'verified',
    isAccessibleRole: true,
    isVeteranFriendly: true,
    status: 'active',
    isDemoData: true,
  },
  {
    id: 'demo-job-8',
    title: 'Assistant Security Officer (Group-B Non-Ministerial Reserved Post)',
    company: 'National Thermal Power Corporation (NTPC Ltd)',
    location: 'Noida, Uttar Pradesh / Pan-India Plants',
    country: 'IN',
    state: 'Uttar Pradesh',
    type: 'full-time',
    sector: 'psu',
    workplaceType: 'on-site',
    industry: 'Energy & Power / PSU',
    experienceLevel: '5-12 Years Service (Ex-Servicemen Reservation)',
    educationRequired: 'Matriculate with 15 years service or Graduate Degree',
    salaryRange: '₹11,50,000 - ₹15,80,000 / annum (E-1 IDA Scale + Township Housing)',
    minSalary: 1150000,
    maxSalary: 1580000,
    description: 'Statutory Ex-Servicemen reservation vacancy. Oversee plant security force, fire response readiness, CISF liaison, VIP security protocols, and security automation at major super thermal power projects.',
    eligibilitySummary: 'Honourably discharged JCOs/NCOs from Indian Army, Navy, or Air Force possessing valid ESM Identity Card. Upper age relaxations per central government reservation orders.',
    applicationProcess: 'Online application through NTPC official careers site (ntpccareers.net) quoting ESM reservation category code. Physical efficiency and document scrutiny.',
    officialUrl: 'https://ntpccareers.net/advt-security-esm-2026',
    veteranFriendlyScore: 97,
    civilianSkillsMatched: ['Industrial Plant Security', 'Emergency Response Command', 'Fire & Safety Drills', 'Liaison with Paramilitary Units'],
    militaryBackgroundSuitability: ['Infantry', 'CMP', 'Armoured Corps', 'Artillery', 'Air Force Security'],
    postedDate: '4 days ago',
    isVerifiedEmployer: true,
    verificationStatus: 'verified',
    isAccessibleRole: false,
    isVeteranFriendly: true,
    status: 'active',
    isDemoData: true,
  },
  {
    id: 'demo-job-9',
    title: 'Defense Systems Integration Apprenticeship (Airframe & Hydraulics)',
    company: 'Hindustan Aeronautics Limited (HAL)',
    location: 'Nashik, Maharashtra / Bengaluru',
    country: 'IN',
    state: 'Maharashtra',
    type: 'apprenticeship',
    sector: 'psu',
    workplaceType: 'on-site',
    industry: 'Defense Tech / Aerospace',
    experienceLevel: 'Agniveer (Technical) or 1-4 Years Technical Trade',
    educationRequired: 'Diploma in Aeronautical/Mechanical or Agniveer Technical Certificate',
    salaryRange: '₹26,000 - ₹32,000 / month (Apprenticeship Act stipend + Hal welfare)',
    minSalary: 312000,
    maxSalary: 384000,
    description: '1-year Apprenticeship Training in aircraft overhaul, composite airframe repair, and hydraulic testing under the Apprentices Act, 1961. Candidates obtaining excellent grade get preferential consideration in permanent technician recruitments.',
    eligibilitySummary: 'Pass-out Agniveer (Air Force IAF Airmen / Navy Artificer / Army Aviation technicians) within 2 years of completing military tenure.',
    applicationProcess: 'Apply through HAL Official Portal (hal-india.co.in) and National Apprenticeship Training Scheme (NATS) portal.',
    officialUrl: 'https://hal-india.co.in/careers/nats-apprenticeship-nashik',
    veteranFriendlyScore: 96,
    civilianSkillsMatched: ['Aerospace Systems Inspection', 'Rigid Quality Calibrations', 'Hydraulic Rig Operations', 'Airframe Structural Repair'],
    militaryBackgroundSuitability: ['Indian Air Force (Airframe/Engines)', 'Naval Air Technical', 'Army Aviation'],
    postedDate: '5 days ago',
    isVerifiedEmployer: true,
    verificationStatus: 'verified',
    isAccessibleRole: false,
    isVeteranFriendly: true,
    status: 'active',
    isDemoData: true,
  },
  {
    id: 'demo-job-10',
    title: 'Junior Corporate Operations Executive',
    company: 'Unverified Third-Party Staffing Agency',
    location: 'New Delhi / Unspecified',
    country: 'IN',
    state: 'Delhi',
    type: 'full-time',
    sector: 'private',
    workplaceType: 'on-site',
    industry: 'Operations',
    experienceLevel: '0-2 Years',
    educationRequired: 'Any 10th/12th Pass',
    salaryRange: '₹6,00,000 - ₹8,00,000 / annum (Unconfirmed)',
    minSalary: 600000,
    maxSalary: 800000,
    description: 'Assisting corporate security and administrative desk tasks. Listing submitted through unverified public third-party agency without official corporate domain verification.',
    eligibilitySummary: 'Open to all ex-servicemen. Listing has not completed GSTIN business verification.',
    applicationProcess: 'Direct link to external form. Note: Never pay any security deposits or processing fees for any recruitment process.',
    officialUrl: 'https://example-unverified-agency.com/apply',
    veteranFriendlyScore: 70,
    civilianSkillsMatched: ['Basic Administration', 'Entry-Level Security'],
    militaryBackgroundSuitability: ['All Trades'],
    postedDate: '6 days ago',
    isVerifiedEmployer: false,
    verificationStatus: 'unverified',
    isAccessibleRole: true,
    isVeteranFriendly: false,
    isDuplicateOrFlagged: true,
    scamReportsCount: 3,
    status: 'active',
    isDemoData: true,
  }
];

export const DEMO_SCHEMES: GovernmentScheme[] = [
  {
    id: 'scheme-dgr-reservation',
    title: 'Ex-Servicemen (ESM) Central Govt & PSU Employment Reservation',
    agency: 'Directorate General Resettlement (DGR) / Department of Ex-Servicemen Welfare (DESW), MoD',
    country: 'IN',
    stateOrRegion: 'Central / Pan-India',
    schemeType: 'central',
    category: 'jobs',
    targetBeneficiaries: ['Ex-Servicemen (ESM)', 'Disabled Ex-Servicemen', 'Widows/Dependents (Priority I-III)'],
    benefitsSummary: 'Statutory 10% horizontal reservation in Group C posts and 20% in Group D posts across Central Govt Ministries, Departments, Public Sector Undertakings (PSUs), and Nationalized Banks, with age relaxations (Military Service + 3 Years).',
    eligibilityCriteria: [
      'Discharged under honorable conditions with verified ESM Identity Card',
      'Minimum color service requirement as per MoD norms',
      'Educational equivalence certificate (e.g., Indian Army Special Certificate of Education equivalent to Matric/Graduation)'
    ],
    applicationProcess: 'Register on DGR official portal and apply against respective SSC, IBPS, UPSC, or PSU recruitment advertisements quoting ESM category.',
    applicationSteps: [
      'Step 1: Obtain ESM Identity Card and discharge book from your respective Zila Sainik Board (ZSB).',
      'Step 2: Obtain Army Graduation/Special Matriculation Certificate if applying under educational equivalence.',
      'Step 3: Register profile on official DGR portal (dgrindia.gov.in) under Job Seeker registration.',
      'Step 4: Quote ESM registration code and category when filling Central Govt / PSU recruitment forms.'
    ],
    documentsRequired: [
      'Original Service Discharge Book',
      'ESM Identity Card issued by ZSB',
      'Pension Payment Order (PPO) copy',
      'Educational Equivalence Certificate'
    ],
    officialPortalUrl: 'https://dgrindia.gov.in',
    lastVerifiedDate: '2026-03-01',
    isDemoData: true,
  },
  {
    id: 'scheme-agniveer-capf',
    title: 'Agniveer 10% Reservation Quota in CAPFs and Assam Rifles',
    agency: 'Ministry of Home Affairs (MHA) & Ministry of Defence (MoD)',
    country: 'IN',
    stateOrRegion: 'Central / Pan-India',
    schemeType: 'central',
    category: 'jobs',
    targetBeneficiaries: ['Former Agniveers (All three service wings: Army, Navy, Air Force)'],
    benefitsSummary: '10% horizontal reservation in Constable (General Duty) recruitments in BSF, CISF, CRPF, ITBP, SSB, and Assam Rifles, plus exemption from Physical Efficiency Test (PET) and upper age relaxation up to 5 years (1st batch) and 3 years subsequently.',
    eligibilityCriteria: [
      'Successful completion of 4-year tenure in the Armed Forces under the Agnipath Scheme',
      'Possession of official Agniveer Skill Certificate and Discharge Dossier'
    ],
    applicationProcess: 'Apply through Staff Selection Commission (SSC GD Constable notification) selecting the Agniveer reservation category.',
    applicationSteps: [
      'Step 1: Download your Agniveer Skill Certificate from Skill India Digital portal or Unit Headquarters.',
      'Step 2: Check SSC official notification for Constable (GD) in Central Armed Police Forces.',
      'Step 3: Fill application on ssc.gov.in using Agniveer enrollment number for age exemption and quota.',
      'Step 4: Present discharge documents during document verification stage.'
    ],
    documentsRequired: [
      'Agniveer Service Completion Certificate',
      'Agniveer Skill Certificate (issued by MoD & MSDE)',
      '10th Standard / Matriculation Certificate'
    ],
    officialPortalUrl: 'https://mha.gov.in',
    lastVerifiedDate: '2026-02-28',
    isDemoData: true,
  },
  {
    id: 'scheme-pmss-scholarship',
    title: "Prime Minister's Scholarship Scheme (PMSS) for Higher Education",
    agency: 'Kendriya Sainik Board (KSB), Department of Ex-Servicemen Welfare, MoD',
    country: 'IN',
    stateOrRegion: 'Central / Pan-India',
    schemeType: 'central',
    category: 'education',
    targetBeneficiaries: ['Ex-Servicemen (ESM) Wards/Widows', 'Former Agniveers pursuing recognized technical degrees'],
    benefitsSummary: 'Monthly financial assistance of ₹3,000/month for girls and ₹2,500/month for boys pursuing approved technical & professional degree courses (BE, B.Tech, MBBS, BDS, MBA, MCA, Pharmacy) recognized by AICTE/UGC.',
    eligibilityCriteria: [
      'Ward/widow of Ex-Servicemen or former service personnel below Officer rank (PBOR)',
      'Minimum 60% marks in 10+2 / Diploma / Graduation entry qualification',
      'Enrolled in 1st year of professional degree course in current academic year'
    ],
    applicationProcess: 'Apply online on Kendriya Sainik Board portal (ksb.gov.in) with ZSB verification.',
    applicationSteps: [
      'Step 1: Register an applicant profile on official KSB website (ksb.gov.in).',
      'Step 2: Upload bonafide certificate from college / institute confirming admission in AICTE/UGC approved course.',
      'Step 3: Submit online form for digital verification by concerned Zila Sainik Welfare Officer.',
      'Step 4: KSB disburses scholarship directly to beneficiary Aadhaar-linked bank account (DBT).'
    ],
    documentsRequired: [
      'ESM Card / Discharge Book of Parent',
      'Bonafide Certificate from College Dean/Principal',
      'Mark sheet of 10+2 / Qualifying Exam (Min 60%)',
      'Aadhaar seeded bank account details'
    ],
    officialPortalUrl: 'https://ksb.gov.in',
    lastVerifiedDate: '2026-02-15',
    isDemoData: true,
  },
  {
    id: 'scheme-dgr-training',
    title: 'DGR Resettlement & Corporate Transition Training Programs',
    agency: 'Directorate General Resettlement (DGR), MoD',
    country: 'IN',
    stateOrRegion: 'Central / Pan-India',
    schemeType: 'central',
    category: 'training',
    targetBeneficiaries: ['Retiring Armed Forces Personnel', 'Ex-Servicemen (ESM)', 'War-Disabled Personnel'],
    benefitsSummary: 'Fully sponsored and subsidized management, executive, IT, and technical certifications conducted at premier institutes including IIMs, XLRI, MDI Gurgaon, and certified vocational bodies.',
    eligibilityCriteria: [
      'Armed forces personnel in final 1-2 years of service or Ex-Servicemen within 3 years of discharge',
      'Willingness to attend full-time or online executive modules'
    ],
    applicationProcess: 'Apply through unit OC / Rajya Sainik Board to DGR Training Directorate.',
    applicationSteps: [
      'Step 1: Consult DGR Annual Training Calendar on dgrindia.gov.in.',
      'Step 2: Submit willingness application to Unit Headquarters / ZSB.',
      'Step 3: Receive DGR sponsorship sponsorship nomination letter for chosen institute.',
      'Step 4: Complete course and participate in corporate transition placement drives organized by the institute.'
    ],
    documentsRequired: [
      'Service Identity Card or Discharge Book',
      'Unit Recommendation / ZSB NOC',
      'Educational qualification certificates'
    ],
    officialPortalUrl: 'https://dgrindia.gov.in',
    lastVerifiedDate: '2026-03-01',
    isDemoData: true,
  },
  {
    id: 'scheme-affdf-disability',
    title: 'Armed Forces Flag Day Fund (AFFDF) Disability & Medical Assistance',
    agency: 'Kendriya Sainik Board (KSB), MoD',
    country: 'IN',
    stateOrRegion: 'Central / Pan-India',
    schemeType: 'central',
    category: 'disability',
    targetBeneficiaries: ['Disabled Ex-Servicemen', 'War-Disabled Soldiers', '100% Disabled Dependents'],
    benefitsSummary: 'Direct financial assistance for treatment, house repair grants, non-pensioner medical relief, and monthly financial sustenance for disabled personnel not receiving disability pensions.',
    eligibilityCriteria: [
      'Disability attributed to or aggravated by military service or civilian disability post-discharge',
      'Verified pension book or non-pensioner certificate certified by Zila Sainik Board'
    ],
    applicationProcess: 'Submit grant application online on KSB portal with medical board proceedings.',
    applicationSteps: [
      'Step 1: Download medical assistance form from ksb.gov.in.',
      'Step 2: Attach Medical Board Disability certificate and civil hospital/ECHS treatment summary.',
      'Step 3: Get endorsement from local Zila Sainik Welfare Officer.',
      'Step 4: KSB transfers grant directly to applicant account.'
    ],
    documentsRequired: [
      'Medical Board Assessment Proceedings (AFMSF-16)',
      'Discharge Book showing cause of discharge',
      'ESM Identity Card',
      'Cancelled Cheque / Bank Passbook'
    ],
    officialPortalUrl: 'https://ksb.gov.in',
    lastVerifiedDate: '2026-01-30',
    isDemoData: true,
  },
  {
    id: 'scheme-semfex-selfemp',
    title: 'SEMFEX-II & III Self-Employment Micro-Credit Schemes',
    agency: 'National Bank for Agriculture and Rural Development (NABARD) & SIDBI',
    country: 'IN',
    stateOrRegion: 'Central / Pan-India',
    schemeType: 'central',
    category: 'self_employment',
    targetBeneficiaries: ['Ex-Servicemen (ESM)', 'Agniveers wanting to launch micro-enterprises', 'Widows of ESM'],
    benefitsSummary: 'Term loan subsidies, soft seed capital assistance, and margin money loans at concessional interest rates for transport services, agro-processing, cold chains, small manufacturing, and renewable energy ventures.',
    eligibilityCriteria: [
      'Ex-Servicemen or eligible service personnel verified by RSB/ZSB',
      'Feasible project proposal for small-scale commercial or agro-industrial unit'
    ],
    applicationProcess: 'Submit project report through Zila Sainik Welfare Office to participating Public Sector Bank / NABARD / SIDBI branch.',
    applicationSteps: [
      'Step 1: Prepare Detailed Project Report (DPR) with estimated capital expenditure.',
      'Step 2: Obtain ESM eligibility certificate from Zila Sainik Board.',
      'Step 3: Submit loan application to nearest participating bank branch with SEMFEX cover.',
      'Step 4: Bank sanctions loan and claims margin money subsidy from NABARD/SIDBI.'
    ],
    documentsRequired: [
      'ZSB Eligibility Certificate',
      'Project Feasibility Report (DPR)',
      'Discharge Book & PAN/Aadhaar',
      'Bank Account Statements'
    ],
    officialPortalUrl: 'https://desw.gov.in',
    lastVerifiedDate: '2026-02-10',
    isDemoData: true,
  },
  {
    id: 'scheme-punjab-pesco',
    title: 'Punjab State Ex-Servicemen Welfare & PESCO Employment Deployment',
    agency: 'Department of Defence Services Welfare, Government of Punjab',
    country: 'IN',
    stateOrRegion: 'Punjab',
    schemeType: 'state',
    category: 'jobs',
    targetBeneficiaries: ['Ex-Servicemen belonging to Punjab State', 'Widows and Dependents of Punjab Veterans'],
    benefitsSummary: '13% reservation in Punjab State Civil Services & Police Recruitments, guaranteed security/management placements through Punjab Ex-Servicemen Corporation (PESCO), and cash in lieu of land grants for Gallantry/War veterans.',
    eligibilityCriteria: [
      'Bonafide resident/domicile of Punjab State with valid ESM Card issued by Punjab ZSB'
    ],
    applicationProcess: 'Register with local District Defence Services Welfare Office (DDSWO) and PESCO portal (pesco.punjab.gov.in).',
    applicationSteps: [
      'Step 1: Register at District Defence Services Welfare Office (DDSWO) in your home district.',
      'Step 2: Enroll on PESCO online portal for state government security, facility, and administrative contracts.',
      'Step 3: Quote Punjab ESM domicile certificate in PPSC / PSSSB state exams for 13% quota.'
    ],
    documentsRequired: [
      'Punjab Domicile Certificate',
      'Discharge Book with Exemplary/Very Good character',
      'ESM Identity Card issued by Punjab DDSWO'
    ],
    officialPortalUrl: 'https://defencewelfare.punjab.gov.in',
    lastVerifiedDate: '2026-02-20',
    isDemoData: true,
  },
  {
    id: 'scheme-haryana-sainik',
    title: 'Haryana Ex-Servicemen Special Employment & Educational Welfare',
    agency: 'Sainik and Ardh Sainik Welfare Department, Government of Haryana',
    country: 'IN',
    stateOrRegion: 'Haryana',
    schemeType: 'state',
    category: 'jobs',
    targetBeneficiaries: ['Haryana Domicile ESM', 'Wards of Ex-Servicemen', 'Paramilitary Retirees'],
    benefitsSummary: '5% horizontal reservation in Group A & B, and 5% in Group C & D Haryana State Civil posts (HPSC/HSSC), cash awards for gallantry winners, and special scholarships for children of non-commissioned personnel.',
    eligibilityCriteria: [
      'Haryana state domicile with valid ESM certificate issued by Haryana Zila Sainik Board'
    ],
    applicationProcess: 'Apply through Haryana Parivar Pehchan Patra (PPP) integrated with Sainik Kalyan portal (hryesw.gov.in).',
    applicationSteps: [
      'Step 1: Link ESM status to Haryana Parivar Pehchan Patra (Family ID).',
      'Step 2: Obtain Haryana ESM Eligibility Certificate from District Sainik Board.',
      'Step 3: Apply for HPSC / HSSC recruitments with verified ESM certificate.'
    ],
    documentsRequired: [
      'Haryana Resident Certificate',
      'Family ID (PPP)',
      'Service Discharge Book',
      'Haryana Zila Sainik Board Certificate'
    ],
    officialPortalUrl: 'https://hryesw.gov.in',
    lastVerifiedDate: '2026-03-05',
    isDemoData: true,
  },
  {
    id: 'scheme-rajasthan-sainik',
    title: 'Rajasthan Sainik Kalyan - 5% to 12.5% State Civil Reservation & Land Schemes',
    agency: 'Sainik Kalyan Vibhag, Government of Rajasthan',
    country: 'IN',
    stateOrRegion: 'Rajasthan',
    schemeType: 'state',
    category: 'welfare',
    targetBeneficiaries: ['Rajasthan Domicile Veterans', 'War Widows (Veer Naris)', 'Disabled Soldiers'],
    benefitsSummary: 'Up to 12.5% reservation in Group C/D and 5% in Group A/B state government services (RPSC / RSMSSB), agricultural and residential land allotment in command areas, and daughters marriage financial assistance.',
    eligibilityCriteria: [
      'Bonafide resident of Rajasthan with verified ESM status'
    ],
    applicationProcess: 'Apply online through Rajasthan SSO Portal (sso.rajasthan.gov.in) under Sainik Kalyan section.',
    applicationSteps: [
      'Step 1: Log in to Rajasthan SSO portal using Jan Aadhaar card.',
      'Step 2: Select Sainik Kalyan Vibhag service and submit ESM verification.',
      'Step 3: Download digital ESM reservation certificate for RPSC/RSMSSB applications.'
    ],
    documentsRequired: [
      'Jan Aadhaar Card',
      'Discharge Book / PPO',
      'Rajasthan Bonafide Domicile Certificate',
      'Zila Sainik Kalyan Adhikari Endorsement'
    ],
    officialPortalUrl: 'https://sainikkalyan.rajasthan.gov.in',
    lastVerifiedDate: '2026-02-18',
    isDemoData: true,
  },
  {
    id: 'scheme-up-sainik',
    title: 'Uttar Pradesh Sainik Kalyan - State Services Quota & Agniveer Police Priority',
    agency: 'Department of Ex-Servicemen Welfare, Government of Uttar Pradesh',
    country: 'IN',
    stateOrRegion: 'Uttar Pradesh',
    schemeType: 'state',
    category: 'jobs',
    targetBeneficiaries: ['UP Resident Ex-Servicemen', 'Agniveers from Uttar Pradesh'],
    benefitsSummary: '5% horizontal reservation in Group B & C posts across UP Public Service Commission (UPPSC) and UPSSSC, along with official government preference for retired Agniveers in UP Police and Provincial Armed Constabulary (PAC) recruitments.',
    eligibilityCriteria: [
      'UP state resident with valid ESM / Agniveer certificate issued by UP District Sainik Welfare Office'
    ],
    applicationProcess: 'Register at District Sainik Welfare and Resettlement Office (DSWRO) and apply via UPPSC/UPPRPB portals.',
    applicationSteps: [
      'Step 1: Register at your local District Sainik Welfare & Resettlement Office in UP.',
      'Step 2: Obtain UP State ESM Certificate format signed by DSWRO.',
      'Step 3: Apply for UP Police / UPSSSC recruitment quoting the certificate number.'
    ],
    documentsRequired: [
      'Service Discharge Book / Agniveer Certificate',
      'UP Domicile Certificate',
      'Aadhaar Card',
      'District Sainik Welfare Office Registration Slip'
    ],
    officialPortalUrl: 'https://sainikkalyan.up.gov.in',
    lastVerifiedDate: '2026-03-02',
    isDemoData: true,
  },
  {
    id: 'scheme-maharashtra-sainik',
    title: 'Maharashtra Sainik Welfare Board (MSWB) - Training Subsidies & Quota',
    agency: 'Department of Sainik Welfare, Government of Maharashtra',
    country: 'IN',
    stateOrRegion: 'Maharashtra',
    schemeType: 'state',
    category: 'training',
    targetBeneficiaries: ['Maharashtra Domicile ESM', 'Veer Patnis (War Widows)', 'Children of ESM'],
    benefitsSummary: '15% reservation in Group C and 15% in Group D state civil posts, vocational course fee reimbursements (up to ₹50,000) for competitive exams (MPSC/Banking), and house tax exemptions for gallantry awardees.',
    eligibilityCriteria: [
      'Domicile of Maharashtra with valid ESM Identity Card issued by District Sainik Welfare Office (DSWO)'
    ],
    applicationProcess: 'Apply online via Mahasainik portal (mahasainik.maharashtra.gov.in) with DSWO verification.',
    applicationSteps: [
      'Step 1: Create profile on mahasainik.maharashtra.gov.in.',
      'Step 2: Upload Discharge book and domicile certificate.',
      'Step 3: Submit application for educational subsidy or reservation certificate.',
      'Step 4: Collect verified digital certificate for MPSC/Civil recruitments.'
    ],
    documentsRequired: [
      'Maharashtra Domicile Certificate',
      'Discharge Certificate / PPO',
      'District Sainik Welfare Office Registration Card'
    ],
    officialPortalUrl: 'https://mahasainik.maharashtra.gov.in',
    lastVerifiedDate: '2026-02-25',
    isDemoData: true,
  },
  {
    id: 'scheme-karnataka-sainik',
    title: 'Karnataka Sainik Welfare - Civil Quota & Housing Assistance',
    agency: 'Department of Sainik Welfare and Resettlement, Government of Karnataka',
    country: 'IN',
    stateOrRegion: 'Karnataka',
    schemeType: 'state',
    category: 'welfare',
    targetBeneficiaries: ['Karnataka Domicile Veterans', 'War Disabled Personnel', 'Widows of ESM'],
    benefitsSummary: '10% horizontal reservation in Group C and Group D Karnataka Civil Services (KPSC/KEA), financial aid for construction of houses under Rajiv Gandhi Rural Housing, and self-employment transport grants.',
    eligibilityCriteria: [
      'Karnataka domicile with valid ESM Identity Card issued by Karnataka Sainik Board'
    ],
    applicationProcess: 'Apply through Seva Sindhu Portal or District Sainik Welfare Office.',
    applicationSteps: [
      'Step 1: Register on Karnataka Seva Sindhu portal (sevasindhu.karnataka.gov.in).',
      'Step 2: Apply for Ex-Servicemen Welfare Schemes and upload discharge documents.',
      'Step 3: Verification conducted by Karnataka DSWO.',
      'Step 4: Quota certificate issued for KPSC/KEA examinations.'
    ],
    documentsRequired: [
      'Karnataka Domicile Certificate',
      'Discharge Book with PPO',
      'Zila Sainik Board Identity Card'
    ],
    officialPortalUrl: 'https://sainikwelfare.karnataka.gov.in',
    lastVerifiedDate: '2026-02-14',
    isDemoData: true,
  },
  {
    id: 'scheme-tamilnadu-texco',
    title: 'Tamil Nadu Ex-Servicemen Corporation (TEXCO) Employment Placements',
    agency: 'Directorate of Ex-Servicemen Welfare, Government of Tamil Nadu',
    country: 'IN',
    stateOrRegion: 'Tamil Nadu',
    schemeType: 'state',
    category: 'jobs',
    targetBeneficiaries: ['Tamil Nadu Domicile Ex-Servicemen', 'Dependents of Deceased Soldiers'],
    benefitsSummary: 'Direct placement in state government departments, public sector undertakings, and universities for security, administrative, technical, and fire-safety roles through TEXCO without intermediary agent deductions.',
    eligibilityCriteria: [
      'Resident of Tamil Nadu with verified ESM registration in District Ex-Servicemen Welfare Office'
    ],
    applicationProcess: 'Register at TEXCO Head Office (Chennai) or local District Ex-Servicemen Welfare Office.',
    applicationSteps: [
      'Step 1: Register in live employment seniority roll at District Ex-Servicemen Welfare Office.',
      'Step 2: Submit willingness for TEXCO state government contractual assignments.',
      'Step 3: Receive call letter based on service seniority and qualification.'
    ],
    documentsRequired: [
      'Discharge Book (Original & Copy)',
      'ESM Identity Card issued by Tamil Nadu DESW',
      'Educational Certificates'
    ],
    officialPortalUrl: 'https://texco.tn.gov.in',
    lastVerifiedDate: '2026-01-28',
    isDemoData: true,
  }
];

export const DEMO_COURSES: LearningCourse[] = [
  {
    id: 'course-1',
    title: 'Military Leadership to Agile Project Management',
    provider: 'ValorBadge Skills Academy (Demo Module)',
    duration: '4 Weeks (Self-paced)',
    level: 'Intermediate',
    civilianSkillGroup: 'Project Management & Leadership',
    isFree: true,
    certificationOffered: true,
    description: 'Map unit command, squad mission planning, and risk mitigation into Scrum ceremonies, Sprint planning, and Jira task orchestration.',
    isDemoData: true,
  },
  {
    id: 'course-2',
    title: 'Modern Warehousing & Supply Chain Analytics',
    provider: 'Apex Logistics Institute',
    duration: '6 Weeks (Evenings)',
    level: 'Intermediate',
    civilianSkillGroup: 'Supply Chain & Logistics',
    isFree: false,
    certificationOffered: true,
    description: 'Understand civilian ERPs (SAP/Oracle), WMS tracking, RFID systems, and vendor procurement workflows for ex-quartermasters and logistics personnel.',
    isDemoData: true,
  },
  {
    id: 'course-3',
    title: 'Foundations of Industrial Safety & ISO 45001 Compliance',
    provider: 'Global Safety Council',
    duration: '3 Weeks (Self-paced)',
    level: 'Beginner',
    civilianSkillGroup: 'EHS & Industrial Safety',
    isFree: true,
    certificationOffered: true,
    description: 'Transform military standard operating procedures (SOPs) and safety inspections into certified commercial plant EHS frameworks.',
    isDemoData: true,
  },
  {
    id: 'course-4',
    title: 'Cyber Incident Response & SOC Operations',
    provider: 'DefSec Training Labs',
    duration: '8 Weeks (Intensive)',
    level: 'Advanced',
    civilianSkillGroup: 'IT & Cybersecurity',
    isFree: false,
    certificationOffered: true,
    description: 'Transition electronic warfare and cryptographic protocol know-how into commercial blue-team SIEM monitoring, threat detection, and mitigation.',
    isDemoData: true,
  }
];

export const DEMO_APPLICATIONS: ApplicationRecord[] = [
  {
    id: 'app-001',
    jobId: 'demo-job-1',
    jobTitle: 'Operations & Fleet Logistics Manager',
    companyName: 'Nexus Supply Chain Logistics Pvt Ltd',
    appliedDate: '2026-03-10',
    status: 'interview_scheduled',
    stage: 'interview',
    interviewDate: '2026-03-19 at 11:30 AM IST',
    interviewMode: 'virtual',
    resumeVersion: 'Civilian_Ops_Resume_v2.pdf',
    notes: 'Virtual panel round with VP of Supply Chain and HR Director. Focus: Fleet safety protocols and multi-hub logistics management.',
    consentProvided: true,
    feedback: 'Commended for structured military convoy logistics translation into commercial warehouse distribution.',
    lastUpdated: '2026-03-12',
    isDemoData: true,
  },
  {
    id: 'app-002',
    jobId: 'demo-job-3',
    jobTitle: 'Senior Network Operations Center (NOC) Analyst',
    companyName: 'CloudWave Telemetry Solutions',
    appliedDate: '2026-03-05',
    status: 'under_review',
    stage: 'applied',
    resumeVersion: 'Technical_Signals_Civilian_v1.pdf',
    notes: 'Application forwarded to Hiring Manager for technical portfolio assessment and civilian networking equivalence review.',
    consentProvided: true,
    lastUpdated: '2026-03-08',
    isDemoData: true,
  },
  {
    id: 'app-003',
    jobId: 'demo-job-2',
    jobTitle: 'Deputy General Manager (Security & Asset Protection)',
    companyName: 'Bharat Electronics Limited (BEL)',
    appliedDate: '2026-02-18',
    status: 'selected',
    stage: 'selected',
    interviewDate: '2026-02-28',
    interviewMode: 'on-site',
    resumeVersion: 'Security_Command_Resume_v3.pdf',
    notes: 'Selection offer letter dispatched under Statutory ESM horizontal quota. Document verification at BEL Corporate Office completed.',
    consentProvided: true,
    feedback: 'High scoring in crisis command simulation, perimeter surveillance design, and defense industrial security standards.',
    lastUpdated: '2026-03-04',
    isDemoData: true,
  },
  {
    id: 'app-004',
    jobId: 'demo-job-5',
    jobTitle: 'Advanced Electro-Mechanical Apprenticeship',
    companyName: 'AeroTech Industrial Manufacturing Ltd',
    appliedDate: '2026-01-15',
    status: 'rejected',
    stage: 'rejected',
    interviewDate: '2026-01-28',
    interviewMode: 'on-site',
    resumeVersion: 'Mechanical_Tech_Resume_v1.pdf',
    notes: 'Candidate overqualified for apprentice role; recruiter recommended applying directly for Senior Production Supervisor grade in Q2 cycle.',
    consentProvided: true,
    feedback: 'Strong praise for EME military discipline; encouraged to explore grade E-2 supervisor positions.',
    lastUpdated: '2026-02-01',
    isDemoData: true,
  }
];

export const DEMO_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-1',
    timestamp: '2026-09-13 07:15:22 UTC',
    actor: 'system_auth_agent',
    action: 'SESSION_INITIALIZE',
    target: 'client_session_sandbox',
    severity: 'info',
    details: 'Encrypted client session established with zero-trust headers. No PII broadcast.',
  },
  {
    id: 'log-2',
    timestamp: '2026-09-13 07:14:05 UTC',
    actor: 'privacy_guard_filter',
    action: 'INPUT_CLASSIFICATION_SCAN',
    target: 'service_profile_inputs',
    severity: 'info',
    details: 'Automated heuristic scan passed: 0 classified/tactical keywords detected.',
  },
  {
    id: 'log-3',
    timestamp: '2026-09-13 07:10:48 UTC',
    actor: 'employer_portal_verifier',
    action: 'EMPLOYER_GSTIN_VALIDATE',
    target: 'Apex FastLog Retail Warehouses',
    severity: 'info',
    details: 'Corporate entity verification verified against registered business registry.',
  }
];

export const DEMO_HEALTH_METRICS: SystemHealthMetric[] = [
  {
    service: 'Client Gateway & Web Services',
    status: 'healthy',
    latencyMs: 24,
    uptimePercent: 99.98,
    lastChecked: 'Just now',
  },
  {
    service: 'Military-Civilian Skill Ontology Engine',
    status: 'healthy',
    latencyMs: 41,
    uptimePercent: 99.95,
    lastChecked: '1 min ago',
  },
  {
    service: 'Privacy Sanitization & Regex Guard',
    status: 'healthy',
    latencyMs: 12,
    uptimePercent: 100.0,
    lastChecked: 'Just now',
  },
  {
    service: 'Role-Based Access Control (RBAC) Subsystem',
    status: 'healthy',
    latencyMs: 18,
    uptimePercent: 99.99,
    lastChecked: '2 mins ago',
  }
];

export interface SkillTranslationMapping {
  militaryRole: string;
  civilianCategory: string;
  civilianJobTitles: string[];
  translatedCoreSkills: string[];
  sampleBulletPoint: string;
}

export const SKILL_TRANSLATION_DATABASE: SkillTranslationMapping[] = [
  {
    militaryRole: 'Infantry Squad / Platoon Leadership',
    civilianCategory: 'Operations & Team Management',
    civilianJobTitles: ['Operations Supervisor', 'Facility Manager', 'Crisis Response Coordinator', 'Field Operations Lead'],
    translatedCoreSkills: [
      'High-Stakes Decision Making',
      'Cross-Functional Team Leadership (10-30 Personnel)',
      'Operational Risk Assessment & Mitigation',
      'Resource Planning Under Uncertainty',
      'Standard Operating Procedure (SOP) Enforcement'
    ],
    sampleBulletPoint: 'Directed cross-functional team of 24 members across complex time-sensitive objectives with 100% adherence to rigorous safety standards and zero equipment loss.'
  },
  {
    militaryRole: 'Signals / Telecommunications / Electronics',
    civilianCategory: 'IT, Networks & Telecommunications',
    civilianJobTitles: ['Network Operations Center (NOC) Engineer', 'Telecommunications Specialist', 'Field Systems Administrator', 'Cyber Security Analyst'],
    translatedCoreSkills: [
      'Radio Frequency & Microwave Communications',
      'High-Reliability Secure Network Deployment',
      'Hardware Diagnostics & Preventive Maintenance',
      'Disaster Recovery & Redundant Failovers',
      'Cryptographic & Security Compliance'
    ],
    sampleBulletPoint: 'Configured, monitored, and maintained high-availability tactical communication networks across 5 remote nodes, sustaining 99.9% uptime in adverse environmental conditions.'
  },
  {
    militaryRole: 'Army Service Corps (ASC) / Quartermaster Logistics',
    civilianCategory: 'Supply Chain, Fleet & Procurement',
    civilianJobTitles: ['Supply Chain Manager', 'Warehouse Operations Lead', 'Fleet Logistics Director', 'Procurement Specialist'],
    translatedCoreSkills: [
      'End-to-End Multimodal Supply Chain Execution',
      'Bulk Inventory Accounting & Audit Reconciliation',
      'Vendor & Contract Delivery Governance',
      'Heavy Fleet Routing & Preventative Maintenance',
      'Hazardous Material & Cold-Chain Storage'
    ],
    sampleBulletPoint: 'Managed allocation, tracking, and warehousing of ₹8 Cr+ in critical stores and provisions; reduced supply turnaround latency by 28% through revised dispatch protocols.'
  },
  {
    militaryRole: 'Corps of Electrical & Mechanical Engineers (EME)',
    civilianCategory: 'Engineering, Plant & Quality Maintenance',
    civilianJobTitles: ['Plant Maintenance Engineer', 'Equipment Reliability Manager', 'Diagnostic Technician', 'Quality Assurance Inspector'],
    translatedCoreSkills: [
      'Heavy Machinery Diagnostic Triaging',
      'Preventative Maintenance Schedules & Root Cause Analysis',
      'Hydraulics, Pneumatics & Power Systems',
      'Spares Forecasting & Workshop Safety Protocols',
      'Technical Documentation & Regulatory Audits'
    ],
    sampleBulletPoint: 'Supervised a specialized technical workshop repairing heavy electro-mechanical assemblies, improving mean-time-between-failures (MTBF) by 34% through proactive inspection cycles.'
  },
  {
    militaryRole: 'Clerks / Adjutant Branch / Personnel Administration',
    civilianCategory: 'Human Resources & Executive Administration',
    civilianJobTitles: ['HR Operations Specialist', 'Office Administrator', 'Compliance & Records Manager', 'Executive Coordinator'],
    translatedCoreSkills: [
      'High-Volume Confidential Records Management',
      'Statutory & Regulatory Policy Compliance',
      'Payroll, Allowances & Benefits Administration',
      'Executive Correspondence & Documentation',
      'Inter-Departmental Stakeholder Coordination'
    ],
    sampleBulletPoint: 'Administered personnel records, career progression documentation, and grievance resolutions for 600+ personnel with 100% compliance with statutory policies and strict data privacy.'
  },
  {
    militaryRole: 'Agniveer (General Service & Modern Technical Disciplines)',
    civilianCategory: 'Fast-Track Operations, Tech Support & Field Services',
    civilianJobTitles: ['Operations Associate', 'Technical Field Executive', 'Logistics Coordinator', 'Customer Support / Quality Associate'],
    translatedCoreSkills: [
      'Exceptional Punctuality & Mission Discipline',
      'Rapid Technology & Drill Adaptability',
      'Physical Endurance & Shift Resilience',
      'Team Synchronization & Clear Escalation Protocol',
      'Safety, Cleanliness & Tool Accountability'
    ],
    sampleBulletPoint: 'Completed 4-year rigorous armed forces tenure demonstrating agile adaptability, team coordination, and faultless execution across diverse logistical and operational assignments.'
  }
];

export interface DemoCandidate {
  id: string;
  name: string;
  militaryBranch: string;
  yearsOfService: number;
  civilianTargetRole: string;
  location: string;
  translatedSkills: string[];
  isDemoData: boolean;
}

export const DEMO_CANDIDATES: DemoCandidate[] = [
  {
    id: 'cand-1',
    name: 'Ex-Subedar Rajesh Sharma',
    militaryBranch: 'Indian Army (ASC)',
    yearsOfService: 18,
    civilianTargetRole: 'Operations & Fleet Logistics Manager',
    location: 'Pune, Maharashtra',
    translatedSkills: ['Multimodal Logistics', 'Fleet Maintenance', 'Inventory Audit', 'Crisis Command'],
    isDemoData: true
  },
  {
    id: 'cand-2',
    name: 'Agniveer Vikramaditya Singh',
    militaryBranch: 'Agniveer (Technical Wing)',
    yearsOfService: 4,
    civilianTargetRole: 'Industrial Field Service Engineer',
    location: 'Bengaluru, Karnataka',
    translatedSkills: ['Electro-mechanical Troubleshooting', 'Tool Accountability', 'Safety SOPs', 'Fast Adaptability'],
    isDemoData: true
  },
  {
    id: 'cand-3',
    name: 'Ex-Master Chief Petty Officer Amit Deshmukh',
    militaryBranch: 'Indian Navy (Electrical Branch)',
    yearsOfService: 15,
    civilianTargetRole: 'Power Infrastructure Maintenance Head',
    location: 'Mumbai, Maharashtra',
    translatedSkills: ['High-voltage Switchgear', 'Preventative Overhaul', 'Marine Logistics', 'Risk Mitigation'],
    isDemoData: true
  },
  {
    id: 'cand-4',
    name: 'Ex-Sergeant Preeti Rawat',
    militaryBranch: 'Indian Air Force (Signals)',
    yearsOfService: 10,
    civilianTargetRole: 'Enterprise Telecommunications Network Lead',
    location: 'Gurugram, Haryana',
    translatedSkills: ['RF Systems', 'Incident Response Runbooks', 'Microwave Link Diagnostics', 'Team Leadership'],
    isDemoData: true
  },
  {
    id: 'cand-5',
    name: 'Ex-Major Sunita Verma',
    militaryBranch: 'Indian Army (Corps of Engineers)',
    yearsOfService: 12,
    civilianTargetRole: 'Corporate Facilities & Physical Security Director',
    location: 'Noida, UP / NCR',
    translatedSkills: ['Facilities Architecture', 'Access Control Systems', 'Crisis Containment', 'Budget Stewardship'],
    isDemoData: true
  }
];

